# production:
#   stage: deploy
#   before_script:
#     - npm config set prefix /usr/local
#     - npm install -g serverless
#   script:
#     - serverless deploy --stage production --verbose
#   environment: production


image: node:node:15.5.1

variables:
  AWS_REGION: us-east-2

stages:
  - deploy_function


production:
  stage: deploy_function
  before_script:
    - FAILURE_MESSAGE="Must define \$AWS_ACCESS_KEY_ID and \$AWS_SECRET_ACCESS_KEY. Add keys to $CI_PROJECT_URL/-/settings/ci_cd"
    - test -z "$AWS_SECRET_ACCESS_KEY" && echo $FAILURE_MESSAGE && exit 1
    - test -z "$AWS_ACCESS_KEY_ID" && echo $FAILURE_MESSAGE && exit 1
  script:
    - npm install
    - npm run deploy -- --stage staging --verbose
  environment: production
  only: 
    - master
