service: ${file(./secret.json):ApiName}
provider:
    name: aws
    runtime: nodejs14.x
    region: ${file(./secret.json):DefaultRegion}
    stage: dev

functions:
    product_search:
        handler: src/lambda/product/product_search.handler
        events:
            - http:
                  path: /api/products/{id_category}/-/{keyword}
                  method: get
            - http:
                  path: /api/products/{id_category}
                  method: get
            - http:
                  path: /api/products/-/{keyword}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    user_access_level_get: #//fake endpoint
        handler: src/lambda/user/user_access_level_get.handler
        events:
            - http:
                  path: /api/user_access_level_get
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    product_details_get:
        handler: src/lambda/product/product_details_get.handler
        events:
            - http:
                  path: /api/product/{id_product_m2m_vendor}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    user_create:
        handler: src/lambda/user/user_create.handler
        events:
            - http:
                  path: /api/user_create/{code}
                  method: post
            - http:
                  path: /api/user_create
                  method: post
        cors: true
        origin: "*"
    #--------------------------------------------------------------------------

    user_verify:
        handler: src/lambda/user/user_verify.handler
        events:
            - http:
                  path: /api/user_verify/{token}
                  method: get
        cors: true
        origin: "*"

    #-------------------------------------------------------------------------

    user_login:
        handler: src/lambda/user/user_login.handler
        events:
            - http:
                  path: /api/user_login
                  method: post
        cors: true
        origin: "*"
    #------------------------------------------------------------------------

    order_update:
        handler: src/lambda/order/order_update.handler
        events:
            - http:
                  path: /api/order_update
                  method: put
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    wishlist_get_all:
        handler: src/lambda/wishlist/wishlist_get_all.handler
        events:
            - http:
                  path: /api/wishlist_get_all
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    user_logout:
        handler: src/lambda/user/user_logout.handler
        events:
            - http:
                  path: /api/user_logout
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    user_name_get:
        handler: src/lambda/user/user_name_get.handler
        events:
            - http:
                  path: /api/user-first-last-get-all
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    product_create:
        handler: src/lambda/product/product_create.handler
        events:
            - http:
                  path: /api/product-create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    shipping_create:
        handler: src/lambda/shipping/shipping_create.handler
        events:
            - http:
                  path: /api/shipping-create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    shipping_update:
        handler: src/lambda/shipping/shipping_update.handler
        events:
            - http:
                  path: /api/shipping-update
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    order_create:
        handler: src/lambda/order/order_create.handler
        events:
            - http:
                  path: /api/order_create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    product_review_create:
        handler: src/lambda/product/product_review_create.handler
        events:
            - http:
                  path: /api/product_review_create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    product_get:
        handler: src/lambda/product/product_get.handler
        events:
            - http:
                  path: /api/product_get/{id_product}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    user_details:
        handler: src/lambda/user/user_details.handler
        events:
            - http:
                  path: /api/user_details/{id_user}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    user_update:
        handler: src/lambda/user/user_update.handler
        events:
            - http:
                  path: /api/user_update
                  method: put
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_create:
        handler: src/lambda/vendor/vendor_create.handler
        events:
            - http:
                  path: /api/vendor_create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_create_now:
        handler: src/lambda/vendor/vendor_create_now.handler
        events:
            - http:
                  path: /api/vendor_create_now
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_review_create:
        handler: src/lambda/vendor/vendor_review_create.handler
        events:
            - http:
                  path: /api/vendor_review_create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_update:
        handler: src/lambda/vendor/vendor_update.handler
        events:
            - http:
                  path: /api/vendor_update/{id_vendor}
                  method: put
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    user_addresses_get:
        handler: src/lambda/user/user_addresses_get.handler
        events:
            - http:
                  path: /api/user_addresses_get/{user_id}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    user_addresses_update:
        handler: src/lambda/user/user_addresses_update.handler
        events:
            - http:
                  path: /api/user_addresses_update
                  method: put
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    order_tracking:
        handler: src/lambda/order/order_tracking.handler
        events:
            - http:
                  path: /api/order_tracking
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_products_get:
        handler: src/lambda/vendor/vendor_products_get.handler
        events:
            - http:
                  path: /api/vendor/{id_vendor}/products
                  method: get
            - http:
                  path: /api/vendor/{id_vendor}/products/{inactive}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendors_get:
        handler: src/lambda/vendor/vendors_get.handler
        events:
            - http:
                  path: /api/vendors/{keyword}
                  method: get
            - http:
                  path: /api/vendors
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_details_get:
        handler: src/lambda/vendor/vendor_details_get.handler
        events:
            - http:
                  path: /api/vendor/{id_vendor}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_full_details:
        handler: src/lambda/vendor/vendor_full_details.handler
        events:
            - http:
                  path: /api/vendor/full/{id_vendor}
                  method: post
        cors: true
        origin: "*"       
    #-------------------------------------------------------------------------
    vendor_earnings_get:
        handler: src/lambda/vendor/vendor_earnings_get.handler
        events:
            - http:
                  path: /api/vendor/{id_vendor}/vendor_earnings
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    user_orders_get:
        handler: src/lambda/user/user_orders_get.handler
        events:
            - http:
                  path: /api/user/orders
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    product_categories_get:
        handler: src/lambda/product/product_categories_get.handler
        events:
            - http:
                  path: /api/product_categories
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    user_password_reset:
        handler: src/lambda/user/user_password_reset.handler
        events:
            - http:
                  path: /api/reset_password/{id_user}
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    user_forgot_password:
        handler: src/lambda/user/user_forgot_password.handler
        events:
            - http:
                  path: /api/forgot_password
                  method: put
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    products_get_all:
        handler: src/lambda/product/products_get_all.handler
        events:
            - http:
                  path: /api/products
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    products_on_promo:
        handler: src/lambda/product/products_on_promo.handler
        events:
            - http:
                  path: /api/promo_products
                  method: get
            - http:
                  path: /api/promo_products/{limit}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    product_newest_arrival:
        handler: src/lambda/product/product_newest_arrival.handler
        events:
            - http:
                  path: /api/product_newest
                  method: get
            - http:
                  path: /api/product_newest/{limit}
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    wishlist_create:
        handler: src/lambda/wishlist/wishlist_create.handler
        events:
            - http:
                  path: /api/wishlist_create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    wishlist_get:
        handler: src/lambda/wishlist/wishlist_get.handler
        events:
            - http:
                  path: /api/wishlist_get
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    cart_create:
        handler: src/lambda/cart/cart_create.handler
        events:
            - http:
                  path: /api/cart_create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    cart_get:
        handler: src/lambda/cart/cart_get.handler
        events:
            - http:
                  path: /api/cart_get
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    referral_code_create:
        handler: src/lambda/referral/referral_code_create.handler
        events:
            - http:
                  path: /api/referral_code_create
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    referral_code_get:
        handler: src/lambda/referral/referral_code_get.handler
        events:
            - http:
                  path: /api/referral_code_get
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    vendor_orders_get:
        handler: src/lambda/vendor/vendor_orders_get.handler
        events:
            - http:
                  path: /api/vendor_orders_get
                  method: post
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------
    comp_leaders_details_get:
        handler: src/lambda/comp/comp_leaders_details_get.handler
        events:
            - http:
                  path: /api/about_us_get
                  method: get
        cors: true
        origin: "*"
    #-------------------------------------------------------------------------

    ######################################################### below are examples

    bye: #This Is an example
        handler: src/middleware/test_res.bye
        events:
            - http:
                  path: /bye
                  method: get
        cors: true
        origin: "*"

    hello: #This Is an example
        handler: src/middleware/test_res.hello
        # vpc:
        #   securityGroupIds:
        #     - Fn::GetAtt: ServerlessVPC.DefaultSecurityGroup
        #   subnetIds:
        #     - Ref: ServerlessSubnetA
        events:
            - http:
                  path: /hello
                  method: get
        cors: true
        origin: "*"

    crud: #This Is an example
        handler: src/middleware/test_query.query
        # vpc:
        #   securityGroupIds:
        #     - Fn::GetAtt: ServerlessVPC.DefaultSecurityGroup
        #   subnetIds:
        #     - Ref: ServerlessSubnetA
        events:
            - http:
                  path: /query
                  method: post
        cors: true
        origin: "*"
        headers: "*"

plugins:
    - serverless-offline
    - serverless-pseudo-parameters
